### ISSUE TITLE
✨ Spring Boot 레포지토리 초기 설정하기

### ISSUE THREAD

**Issue by rkskekzzz** [80000Coding/80000Coding-Backend#6]
## 할일
 - spring boot jpa
 - gradle

**Comment by psychology50** [comment]
## 개발 환경


- IntelliJ
- Postman
- GitHub
- VMware (Linux)
- Notion

## 스택


### Framework & Library

- Java 17 openjdk
- SpringBoot 3.0.8
- SpringBoot Security
- Spring Data JPA
- Swagger
- Lombok
- OAuth2

### Build tool

- Gradle

### Database

- MySQL 8.0
- Redis

### Infra

- AWS EC2
- AWS S3
- AWS CodeDeploy
- AWS Route53
- Docker & Kubernetes
- Jenkins
- Github Todo bot

**Comment by psychology50** [comment]
https://start.spring.io/
